### ISSUE TITLE
Spawn garbage collector only once

### ISSUE THREAD

**Issue by Thyra** [kemalcr/kemal-session#1]
Right now there is some chaos with the garbage collector: You spawn a gc fiber every time a Session object is created. That happens at least once every HTTP request. So after a short time, you will have hundreds of gc fibers running.
Additionally, the memory engine sleeps in its run_gc method on line 50. So now the gc interval is twice as long as the user intends.

My initial solution looked like this [[1](https://github.com/kemalcr/kemal-session/blob/dcf064c7bb0ed5692d0f05f1b560aa0b8c4bb054/src/kemal-session/gc.cr)]:
```crystal
# @TODO would it be better to not wrap this inside the class?
# What difference does it make?

class Session

  spawn do
    loop do
      Session.config.engine.run_gc
      sleep(Session.config.gc_interval.total_seconds)
    end
  end

end
```
It is probably not perfect but it makes sure that there is only one instance running independently of how many sessions are active. I also like its simplicity (instead of using a singleton pattern for example).
But maybe someone has a better idea?

**Comment by sdogruyol** [comment]
@Thyra i agree with you that we need to improve this.

How about having a seperate `GC` singleton which handles these and only intiliazed on engine start?
