### ISSUE TITLE
Destroy Session

### ISSUE THREAD

**Issue by jasonl99** [kemalcr/kemal-session#10]
I can't figure out how to destroy a session.  In other words, when a user logs out, I want to create a brand new session when/if they log back in.  How do I do this?

**Comment by Thyra** [comment]
:-D
We are working on exactly this at the moment: #7 .

**Comment by jasonl99** [comment]
Thanks!  For now, I'm just adding a bool:

```crystal
context.session.bool("authenticated", true) # when logged in
context.session.bool("authenticated", false) # when logged out
```

**Comment by neovintage** [comment]
@jasonl99 we merged the other pull request. You can now destroy sessions:

```
context.session.destroy
```

We can prob close this issue. Note that we still need to update the redis and file system session engines.

**Comment by sdogruyol** [comment]
@neovintage yup, we need to update those 👍

**Comment by jasonl99** [comment]
Awesome, thank you.
