### ISSUE TITLE
Memory engine not working with objects properly

### ISSUE THREAD

**Issue by neovintage** [kemalcr/kemal-session#17]
I've been looking at the implementation of memory engine and I don't think it's correct. Memory Engine should be serializing and unserializing the storable objects as a more true representation of what other engines (file, redis) should be doing. I didn't want to lose track of this, so putting as an issue for now. I don't know if I'll get the time to fix this soon. Could use some help if others do.

**Comment by neovintage** [comment]
See discussion on #19

**Comment by sdogruyol** [comment]
Fixed via #19
