### ISSUE TITLE
compile failure with v0.21.0

### ISSUE THREAD

**Issue by rdp** [kemalcr/kemal-session#32]
`undefined constant StorableObjects (did you mean 'StorableObject')`

```

expanding macro
in macro 'mapping' /usr/local/Cellar/crystal-lang/0.21.0/src/json/mapping.cr:62, line 86:
...
> 86.       @objects : Hash(String, StorableObjects)
```

full trace here: https://gist.github.com/rdp/56278db479a403b83331f33aebd71167

**Comment by jasonl99** [comment]
This can be fixed with changes to the files in engine (file.cr and memory.cr), where `define_storage` and `define_delegators` are located.  The StorableObjects type needs to be fully-qualified as `Session::StorableObject::StorableObjects`  (there are a total of four places it needs to be changed)

        int: Int32,
        bigint: Int64,
        string: String,
        float: Float64,
        bool: Bool,
        # was not fully-qualified
        # object: StorableObjects
        object: Session::StorableObject::StorableObjects
      })

**Comment by rdp** [comment]
OK that worked thanks! (for followers, anywhere that was `object: StorableObjects` ->  `object: Session::StorableObject::StorableObjects`)

**Comment by crisward** [comment]
I'm also getting this - 
```
in macro 'abstract_engine' /websites/duocms6/lib/kemal-session/src/kemal-session/engine.cr:4, line 16:
#(skipped macro dump)....
abstract `def Session::Engine#int(session_id : String, k : String, v : Int32)` must be implemented by Session::FileEngine
```

**Comment by crisward** [comment]
@sdogruyol I don't mind doing a pull request for this, have already updated the code

**Comment by sdogruyol** [comment]
@crisward please do so 👍

**Comment by rdp** [comment]
thanks!
