### ISSUE TITLE
Rename Session class

### ISSUE THREAD

**Issue by karhatsu** [kemalcr/kemal-session#39]
I added `kemal-csrf` to our project and as you know, it depends on this shard. This broke our application since it also had a class named `Session`. It wasn't quite obvious right away what the problem was when the code didn't compile. Anyway, I was able to fix the issue by renaming our `Session` class.

So how about if the `Session` class in this library would be either renamed to `KemalSession` or `Kemal::Session`? It would be quite an easy change to prevent similar issues in the other projects.

**Comment by sdogruyol** [comment]
@karhatsu yeah `Kemal::Session` is definitely the way to go 👍
