### ISSUE TITLE
Generally methods ending in  ? return bool

### ISSUE THREAD

**Issue by rohanthewiz** [kemalcr/kemal-session#4]
Sdogruyol, thanks for making the 'killer app' of crystal!

The syntax of .int?("blah") below is a bit confusing. Why is the ? necessary?
Generally when I see a question sign, I am expecting a boolean return.

```ruby
get "/get" do |env|
  num  = env.session.int("number") # get the value of "number"
  env.session.int?("hello") # get value or nil, like []?
  "Value of random number is #{num}."
end
```

**Comment by sdogruyol** [comment]
@rohanthewiz thanks for your kind words.

I agree that this is a bit confusing. `int?` is more like a safer version of `int` which won't raise unless the key is not found.

P.S: I'm open to suggestions

**Comment by rohanthewiz** [comment]
Hmm, the session is sometimes called the "session hash". So I see the need for the safe version. The normal behavior of a hash is to return nil if the key not found.
Ideally it would have been nice to not worry about raising an exception at all and simply return a value or nil -- separate concerns, but then you don't want to break backwards compatibility if you don't have to...

Ah! Rename the unsafe to `int!` and the safe to `int`.
Yes, it would break backwards compatibility but it is definitely the Ruby way.
It's just a suggestion though. Thanks for being open.

PS. I think the bang is a great way to express an unexpected behavior as (again) we are thinking "session hash" and hashes normally return nil. You might find this article interesting: https://dev.to/tom/communicating-intent-the-perpetually-misunderstood-ruby-bang

Keep up the great work!

**Comment by sdogruyol** [comment]
@rohanthewiz `!` is mostly for behaviour that alters or changes the underlying structures. IMHO that's not suitable for this case

**Comment by Thyra** [comment]
I chose the `int?(key)` syntax on the basis of the `[key]?` hash method. If we make this the default behaviour for `int(key)` (i.e. no more errors thrown for unknown keys, but simply return nil in these cases), it will create problems because then the return type is always `(Int32 | Nil)` and you can't even do this anymore:
```
Session.int("hi") + 3
```
Because nil has no `+` method. I advise to stick with the current solution unless there is a change concerning this in the crystal language itself.

**Comment by rohanthewiz** [comment]
Thanks Thyra, that makes a lot of sense!
@sdogruyol -- just sharing: As the crystal community grows (and I predict this will be one of the top languages in the near future) it is important for the standards to be established early.  This is a chance to "do over". So just for consideration (I know this is a different language), here's Matz on bang methods: 

> The bang (!) does not mean "destructive" nor lack of it mean non
destructive either.  The bang sign means "the bang version is more
dangerous than its non bang counterpart; handle with care".  Since
Ruby has a lot of "destructive" methods, if bang signs follow your
opinion, every Ruby program would be full of bangs, thus ugly.

Source: https://www.ruby-forum.com/topic/176830#773946

Thank you. Crystal rocks!

**Comment by sdogruyol** [comment]
@rohanthewiz thank you for your feedback and kind words 👍 This is not a Crystal convention but what we chose for this special case.
