### ISSUE TITLE
`Abstract must be implemented by Session::RedisEngine` Error

### ISSUE THREAD

**Issue by oltmannsdaniel** [kemalcr/kemal-session#49]
Error Message:
```
Error in lib/kemal-session/src/kemal-session/engine.cr:81: expanding macro

  abstract_engine({
  ^

in macro 'abstract_engine' lib/kemal-session/src/kemal-session/engine.cr:4, line 75:

.......

> 75.         abstract def object(session_id : String, k : String, v : Session::StorableObject::StorableObjectContainer)

.......

abstract `def Session::Engine#object(session_id : String, k : String, v : Session::StorableObject::StorableObjectContainer)` must be implemented by Session::RedisEngine
```

Yes I am using `neovitage/kemal-session-redis` but there are some issues so I use `progdo/kemal-session-redis`. Whether I am using mine or neovitage`s, there is this error.

@sdogruyol @neovintage

**Comment by neovintage** [comment]
I know what has to be done but it's going to take me a little while to get to this. I know the redis engine needs updating.

**Comment by oltmannsdaniel** [comment]
@neovintage I want to use Crystal in production so yeah. Thanks for helping.

Sure it is all beta stuff, but my product will be beta as well. No worries :D

**Comment by oltmannsdaniel** [comment]
So when I need it now in my current projecr I need to repair it myself right? @neovintage

**Comment by neovintage** [comment]
This is a really bad week for me. I work on kemal-session and the engines in my spare time. If you absolutely need to go to production this week then you might have to fix it. If you create a PR against my redis engine repo I can review it this week. Otherwise, I don't anticipate fixing it until next week.

**Comment by neovintage** [comment]
@oltmannsdaniel can you close this issue? I had a few minutes and cut a new release on the redis engine.

**Comment by sdogruyol** [comment]
Thank you @neovintage 👍
