### ISSUE TITLE
Instantiation of New Engines

### ISSUE THREAD

**Issue by neovintage** [kemalcr/kemal-session#5]
I'm trying to write a redis storage engine and I'm a bit confused by the initialization of the engine in kemal-session. 

When configuring a new engine in kemal, you need to initialize it like the example:
```
Session.config.engine = Session::FileSystemEngine.new({sessions_dir: "/var/foobar/sessions/"})
```

Does this mean that every request that is received by kemal creates a new instantiation of the `FileSystemEngine`?

**Comment by sdogruyol** [comment]
@neovintage nope it does not. It's a singleton https://github.com/kemalcr/kemal-session/blob/master/src/kemal-session/config.cr#L3

**Comment by neovintage** [comment]
@sdogruyol ah, you know what. I forgot that `HTTP::Server` is using fibers and that really, this will only ever run at one time.  I know what to do now. 

Also, the wiki doc on creating engines was a bit confusing for me. Can I suggest edits?
