### ISSUE TITLE
Nil value error

### ISSUE THREAD

**Issue by ozergul** [kemalcr/kemal-session#65]
Hello guys
I am very new to crystal and I stucked at something si mple.

I am using [Crecto](https://github.com/Crecto/crecto) and coding a simple website. All I want to do is store `user_id` variable in session.

```crystal
changeset = Repo.insert(new_user)
if changeset.valid? == false
  puts "Changeset is invalid"
  env.response.status_code = 500
else
  puts "\nThe item was successfully ADDED. ID:#{changeset.instance.id}\n"
  #Here-----> env.session.int("user_id", changeset.instance.id)
  resp(env, {"message": "Success.", "state": true})
end
```

Getting this error:
```
no overload matches 'Kemal::Session#int' with types String, (Int32 | Nil)
Overloads are:
 - Kemal::Session#int(k : String, v : Int32)
 - Kemal::Session#int(k : String)
Couldn't find overloads for these types:
 - Kemal::Session#int(String, Nil)

        env.session.int("user_id", changeset.instance.id)

```

It says `changeset.instance.id `is nil but it is not nil. I really wonder the reason.
Thanks in advance.

**Comment by sdogruyol** [comment]
`(Int32 | Nil)` means that `changeset.instance.id` can be nil, the best practice is to handle the nil case however if you're sure it's not you can do something like `changeset.instance.not_nil!.id`

**Comment by ozergul** [comment]
Your way also is not working.. I tried everything but gives error. 

I think problem is not kemal-session, I tried [topaz db wrapper](https://github.com/topaz-crystal/topaz/tree/master/samples) and worked successfully. Thanks for your reply.
