### ISSUE TITLE
Crystal 0.27.0 breaking change - Time

### ISSUE THREAD

**Issue by lebogan** [kemalcr/kemal-session#70]
I ran into errors like this involving Time#epoch:
```
Error in lib/kemal-session/src/kemal-session/engines/memory.cr:52: expanding macro 
    defne_storage
undefined method 'epoch_ms' for Time
```
I have managed to fix these errors in my local copy as long as I don't update kemal-session. Since I am not a professional developer (newb), I hesitate to do a fork and pull request.

Refererce Crystal breaking change #6662

Thank you.

**Comment by sdogruyol** [comment]
Fixed via https://github.com/kemalcr/kemal-session/releases/tag/v0.11.0

**Comment by duraki** [comment]
We are not able to use this release till you unlock or tag the version on `kemal-csrf` [here](https://github.com/kemalcr/kemal-csrf/blob/master/shard.yml#L7).
