### ISSUE TITLE
TravisCI Integration

### ISSUE THREAD

**Issue by Thyra** [kemalcr/kemal-session#9]
@sdogruyol I think it would be nice to have TravisCI check the code and run specs when reviewing big pull requests like #7 . It would add some additional safety and we can be sure we don't accidentally break something... WDYT?

**Comment by sdogruyol** [comment]
Sure 👍

**Comment by sdogruyol** [comment]
Closed via https://github.com/kemalcr/kemal-session/blob/master/.travis.yml
