### ISSUE TITLE
What is the license of this project?

### ISSUE THREAD

**Issue by ktkiiski** [kemalcr/kemal-session#90]
The project is missing a `LICENSE` file, so I was wondering under what license is this project released? I see the related projects being released under MIT, so is this under MIT as well?

**Comment by toddsundsted** [comment]
potentially going to be hard to nail down. this project is based on code from https://github.com/Thyra/kemal-session by another author, which also does not have an explicit license.

**Comment by sdogruyol** [comment]
Actually this should follow the LICENSE in Kemal 👍 I'm gonna add it now.
